import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import type { MemoryExportMessage } from "./types.ts";

function todayString(): string {
  return new Date().toISOString().slice(0, 10);
}

const FILE_HEADER = (date: string) =>
  `# Memory — ${date}\n\n> Auto-generated by ClawSessionScrubber. Edit freely.\n`;

function formatSection(messages: MemoryExportMessage[], sessionId: string): string {
  const now = new Date().toISOString();
  let out = `\n## Curated from session ${sessionId} — ${now}\n\n`;
  out += `**Messages exported:** ${messages.length}\n\n---\n`;
  for (const msg of messages) {
    out += `\n### [${msg.timestamp}] ${msg.kind}\n\n${msg.textContent}\n\n---\n`;
  }
  return out;
}

export async function writeMemory(
  dataDir: string,
  messages: MemoryExportMessage[],
  date?: string
): Promise<string> {
  if (!messages || messages.length === 0) {
    throw new Error("messages array must not be empty");
  }

  const resolvedDate = date ?? todayString();
  const memoryDir = join(dataDir, "memory");
  const filePath = join(memoryDir, `${resolvedDate}.md`);

  try {
    await mkdir(memoryDir, { recursive: true });
  } catch (err) {
    throw new Error(`Cannot create memory directory: ${(err as Error).message}`);
  }

  let existingContent = "";
  let fileExists = false;
  try {
    existingContent = await readFile(filePath, "utf8");
    fileExists = true;
  } catch {
    // file doesn't exist yet
  }

  const sessionId = messages[0]?.sessionId ?? "unknown";
  const section = formatSection(messages, sessionId);

  let newContent: string;
  if (!fileExists) {
    newContent = FILE_HEADER(resolvedDate) + section;
  } else {
    newContent = existingContent + section;
  }

  try {
    await writeFile(filePath, newContent, "utf8");
  } catch (err) {
    throw new Error(`Cannot write memory file: ${(err as Error).message}`);
  }

  return filePath;
}
