import { describe, it, expect, beforeEach, afterEach } from "bun:test";
import { writeMemory } from "../lib/memoryWriter.ts";
import { rm, mkdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import type { MemoryExportMessage } from "../lib/types.ts";
import os from "node:os";

const TEST_DIR = join(os.tmpdir(), `claw-test-memory-${Date.now()}`);

const SAMPLE_MESSAGES: MemoryExportMessage[] = [
  {
    sessionId: "session-abc",
    id: "msg-1",
    timestamp: "2026-02-25T05:18:55.858Z",
    kind: "user",
    textContent: "Move DE-16 to top priority",
  },
  {
    sessionId: "session-abc",
    id: "msg-2",
    timestamp: "2026-02-25T05:19:12.471Z",
    kind: "assistant",
    textContent: "I've moved DE-16.",
  },
];

beforeEach(async () => {
  await mkdir(TEST_DIR, { recursive: true });
});

afterEach(async () => {
  await rm(TEST_DIR, { recursive: true, force: true });
});

describe("writeMemory", () => {
  it("creates a new file with header when file does not exist", async () => {
    const path = await writeMemory(TEST_DIR, SAMPLE_MESSAGES, "2026-01-01");
    const content = await readFile(path, "utf8");
    expect(content).toContain("# Memory — 2026-01-01");
    expect(content).toContain("Auto-generated by ClawSessionScrubber");
  });

  it("appends to existing file without overwriting header", async () => {
    await writeMemory(TEST_DIR, SAMPLE_MESSAGES, "2026-01-01");
    await writeMemory(TEST_DIR, SAMPLE_MESSAGES, "2026-01-01");
    const filePath = join(TEST_DIR, "memory", "2026-01-01.md");
    const content = await readFile(filePath, "utf8");
    // Header appears only once
    const headerCount = (content.match(/# Memory — 2026-01-01/g) ?? []).length;
    expect(headerCount).toBe(1);
    // But the section appears twice
    const sectionCount = (content.match(/Curated from session/g) ?? []).length;
    expect(sectionCount).toBe(2);
  });

  it("written section contains session ID, kind, and text content", async () => {
    const path = await writeMemory(TEST_DIR, SAMPLE_MESSAGES, "2026-01-01");
    const content = await readFile(path, "utf8");
    expect(content).toContain("session-abc");
    expect(content).toContain("user");
    expect(content).toContain("Move DE-16 to top priority");
  });

  it("uses today's date in filename when date is omitted", async () => {
    const path = await writeMemory(TEST_DIR, SAMPLE_MESSAGES);
    const today = new Date().toISOString().slice(0, 10);
    expect(path).toContain(today);
  });

  it("respects explicit date override", async () => {
    const path = await writeMemory(TEST_DIR, SAMPLE_MESSAGES, "2025-12-31");
    expect(path).toContain("2025-12-31.md");
  });

  it("returns absolute path of the written file", async () => {
    const path = await writeMemory(TEST_DIR, SAMPLE_MESSAGES, "2026-01-01");
    expect(path.startsWith("/")).toBe(true);
    // File actually exists
    const content = await readFile(path, "utf8");
    expect(content.length).toBeGreaterThan(0);
  });

  it("throws an error when messages array is empty", async () => {
    expect(writeMemory(TEST_DIR, [], "2026-01-01")).rejects.toThrow();
  });
});
